# Generated by Django 5.0.2 on 2024-03-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReletion',
            new_name='UserRelation',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
