# Generated by Django 5.0.2 on 2024-03-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chat_code_comment_code_message_code_post_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='code',
            field=models.CharField(blank=True, default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='code',
            field=models.CharField(blank=True, default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
