# Generated by Django 5.0.2 on 2024-03-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_chat_users_alter_postfiles_post_chatuser'),
        ('main', '0006_alter_chat_code_alter_comment_code_and_more'),
    ]

    operations = [
    ]
